name: Test

on: [push, pull_request]

jobs:
  build_and_test:
    name: Test project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - run: cargo test --verbose -- --show-output